### ISSUE TITLE
Idea - Video sample (From QHY183c Camera/Meike Lens) of Airplane (with timestamp & lat/long)

### ISSUE THREAD

**Issue by danlohman** [Sky360-Repository/sky360#17] opened 2023-06-15 05:28 UTC
I'm looking for a video sample captured from the QHY183c and the Meike 3.5mm fisheye lens of an airplane flying though the field of view.  I'm looking for a video with the data below.  Thanks!

 - Time stamp 
 - Approximate Latitude 
 - Approximate Longitude

**Comment by realsnick** [comment] 2023-06-20 14:20
duplicate of #16

**Closed by realsnick** 2023-06-20 14:20 UTC
Labels: Idea
